#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
6.1.1 (A1): 量化术语词条数据 (单一数据源)

每条: key / term(中文名) / definition(一句话定义) / calc(计算口径) / category(分类)
前端浮层与术语表页按 key 在 i18n 取本地化文本, 此处中文作为兜底与语义唯一来源。
"""
from typing import List, Dict

# 分类: 宏观 / 策略 / 因子 / 技术 / 短线 / 数据源 / 产品
GLOSSARY: List[Dict] = [
    # ── 宏观 ────────────────────────────────
    {"key": "merrill_clock", "term": "美林时钟", "category": "宏观",
     "definition": "按经济增长与通胀四象限划分宏观周期的投资时钟模型。",
     "calc": "增长与通胀两轴 → 复苏/过热/滞涨/衰退四阶段"},
    {"key": "recovery", "term": "复苏期", "category": "宏观",
     "definition": "增长回升、通胀低位，权益与债券均有配置价值的阶段。",
     "calc": "增长上行 + 通胀下行"},
    {"key": "overheat", "term": "过热期", "category": "宏观",
     "definition": "增长与通胀同向上行，商品与资源占优、债券承压的阶段。",
     "calc": "增长上行 + 通胀上行"},
    {"key": "stagflation", "term": "滞胀期", "category": "宏观",
     "definition": "增长走弱、通胀高企，现金占优、股债双弱的阶段。",
     "calc": "增长下行 + 通胀上行"},
    {"key": "recession", "term": "衰退期", "category": "宏观",
     "definition": "增长与通胀同步下行，债券占优的阶段。",
     "calc": "增长下行 + 通胀下行"},
    {"key": "merrill_score", "term": "五维评分", "category": "宏观",
     "definition": "美林时钟的定量评分，由五个维度打分合成阶段判断。",
     "calc": "五维度(增长/通胀/流动性/估值/情绪)加权得分"},
    # ── 策略 ────────────────────────────────
    {"key": "momentum", "term": "动量策略", "category": "策略",
     "definition": "买入近期强势股、卖出弱势股的截面策略。",
     "calc": "按近 N 日收益率排名取前 K 只"},
    {"key": "reversal", "term": "反转策略", "category": "策略",
     "definition": "买入短期超跌股、回避涨幅过大的股票。",
     "calc": "按近 N 日收益率排名取后 K 只(超跌反转)"},
    {"key": "quality", "term": "质量策略", "category": "策略",
     "definition": "偏好高盈利质量、低负债、稳定现金流的公司。",
     "calc": "ROE/毛利率/负债率/现金流等质量因子合成"},
    {"key": "capital_flow", "term": "资金流策略", "category": "策略",
     "definition": "跟随主力/北向/板块资金流向选股。",
     "calc": "个股与板块资金净流入趋势评分"},
    {"key": "consensus", "term": "共识榜", "category": "策略",
     "definition": "多套策略交叉验证后共同入选的股票榜单。",
     "calc": "各策略入选集合取交集/计数排序"},
    {"key": "in_pool", "term": "入池", "category": "策略",
     "definition": "某股票新进入某策略选股池。",
     "calc": "当日入选且昨日未入选"},
    {"key": "out_pool", "term": "出池", "category": "策略",
     "definition": "某股票从某策略选股池退出。",
     "calc": "昨日入选且当日未入选"},
    # ── 因子 ────────────────────────────────
    {"key": "factor", "term": "因子", "category": "因子",
     "definition": "影响股票收益的某类可量化特征，如估值、动量、质量。",
     "calc": "单因子 = 一个可计算的截面指标"},
    {"key": "factor_ic", "term": "因子IC", "category": "因子",
     "definition": "因子值与未来收益的秩相关，衡量因子预测力。",
     "calc": "Spearman 秩相关(因子值, 未来N日收益)"},
    {"key": "ic_decay", "term": "IC衰减", "category": "因子",
     "definition": "因子预测力随持有期延长的下降速度。",
     "calc": "分别计算 1/5/10/20 日 IC 观察衰减"},
    {"key": "zscore", "term": "Z-Score", "category": "因子",
     "definition": "标准化后的因子值，衡量偏离均值的标准差数。",
     "calc": "(因子值-均值)/标准差"},
    {"key": "pe", "term": "市盈率(PE)", "category": "因子",
     "definition": "股价相对每股盈利的倍数，衡量估值水平。",
     "calc": "市值/归母净利润"},
    {"key": "pb", "term": "市净率(PB)", "category": "因子",
     "definition": "股价相对每股净资产的倍数。",
     "calc": "市值/净资产"},
    {"key": "roe", "term": "净资产收益率(ROE)", "category": "因子",
     "definition": "股东权益的盈利效率，衡量公司赚钱能力。",
     "calc": "净利润/平均净资产"},
    {"key": "market_cap", "term": "总市值", "category": "因子",
     "definition": "公司全部股份按市价计算的总价值。",
     "calc": "总股本×股价"},
    # ── 技术 ────────────────────────────────
    {"key": "ma", "term": "均线(MA)", "category": "技术",
     "definition": "一定周期收盘价的算术平均，衡量趋势方向。",
     "calc": "近 N 日收盘价均值"},
    {"key": "macd", "term": "MACD", "category": "技术",
     "definition": "由快慢均线差(DEA/DIF)构成的趋势指标。",
     "calc": "EMA12-EMA26 的 DIF 与 9 日 DEA 关系"},
    {"key": "rsi", "term": "RSI", "category": "技术",
     "definition": "衡量近期涨跌强弱相对强度，判断超买超卖。",
     "calc": "N 日平均涨幅/(平均涨幅+平均跌幅)×100"},
    {"key": "kdj", "term": "KDJ", "category": "技术",
     "definition": "随机指标，衡量收盘价在近期高低区间的位置。",
     "calc": "RSV → K/D 平滑 → J=3K-2D"},
    {"key": "volume_ratio", "term": "量比", "category": "技术",
     "definition": "当日每分钟均量相对过去 5 日同期均量的倍数。",
     "calc": "当日累计均量/过去5日同时段均量"},
    {"key": "turnover", "term": "换手率", "category": "技术",
     "definition": "当日成交股数占流通股数的比例，衡量活跃度。",
     "calc": "成交量/流通股本×100%"},
    # ── 短线 ────────────────────────────────
    {"key": "zt_pool", "term": "涨停池", "category": "短线",
     "definition": "当日封住涨停的全部股票列表。",
     "calc": "收盘价触及涨停价且封单未撤"},
    {"key": "zha_ban", "term": "炸板", "category": "短线",
     "definition": "盘中曾涨停但收盘未封住的股票。",
     "calc": "盘中最高触及涨停价、收盘低于涨停价"},
    {"key": "dt_pool", "term": "跌停池", "category": "短线",
     "definition": "当日封住跌停的全部股票列表。",
     "calc": "收盘价触及跌停价"},
    {"key": "lhb", "term": "龙虎榜", "category": "短线",
     "definition": "交易所披露的异动股买卖席位明细。",
     "calc": "按涨跌幅/换手/振幅等条件触发披露"},
    {"key": "ladder", "term": "连板", "category": "短线",
     "definition": "连续多个交易日涨停的股票，连板数越高情绪越强。",
     "calc": "连续涨停天数"},
    {"key": "promote_rate", "term": "晋级率", "category": "短线",
     "definition": "上一梯队连板股中今日继续封板的比例。",
     "calc": "今日晋级N+1板数/昨日N板数"},
    {"key": "money_effect", "term": "赚钱效应", "category": "短线",
     "definition": "市场整体赚钱难易程度的量化读数。",
     "calc": "涨停数/连板高度/晋级率等复合指标"},
    {"key": "sentiment_cycle", "term": "情绪周期", "category": "短线",
     "definition": "短线情绪由冰点到高潮再回落的循环阶段。",
     "calc": "近10日情绪读数相对位置分档"},
    {"key": "sector_flow", "term": "板块资金流", "category": "短线",
     "definition": "行业/概念板块的主力资金净流入流出。",
     "calc": "板块内个股资金流汇总"},
    # ── 数据源 ──────────────────────────────
    {"key": "tushare", "term": "Tushare", "category": "数据源",
     "definition": "开源财经数据接口平台，本产品主要数据源之一。",
     "calc": "需 Token 鉴权的 Pro 接口"},
    {"key": "akshare", "term": "AKShare", "category": "数据源",
     "definition": "开源金融数据接口库，作为兜底数据源。",
     "calc": "爬取公开财经页面并结构化"},
    {"key": "sxsc", "term": "sxsc", "category": "数据源",
     "definition": "山证行情网关，短线三池/龙虎榜等优先调度源。",
     "calc": "网关 Token 鉴权的高频数据接口"},
    {"key": "hot_standby", "term": "三源热备", "category": "数据源",
     "definition": "sxsc→tushare→akshare 依次尝试，自动降级不中断。",
     "calc": "源失败连续3次进入 300s 冷却"},
    {"key": "pit", "term": "PIT(时点数据)", "category": "数据源",
     "definition": "仅使用当时已公开的数据，避免前视偏差。",
     "calc": "评估/回测/因子以 as_of 时点快照为准"},
    {"key": "survivorship", "term": "幸存者偏差", "category": "数据源",
     "definition": "只统计现存标的导致的历史表现虚高。",
     "calc": "纳入退市/改名标的的 PIT 注册表校正"},
    # ── 产品 ────────────────────────────────
    {"key": "ai_eval", "term": "AI评估", "category": "产品",
     "definition": "多模型对个股进行综合评估并给出评级与理由。",
     "calc": "技术指标注入 prompt，多模型串行表决"},
    {"key": "ai_chat", "term": "智能问股", "category": "产品",
     "definition": "对话式个股分析，流式输出多维解读。",
     "calc": "技术面+基本面+策略面融合问答"},
    {"key": "backtest", "term": "回测", "category": "产品",
     "definition": "用历史数据验证策略表现，含成本与前视控制。",
     "calc": "信号→T+1成交→扣除成本计算净值"},
    {"key": "walkforward", "term": "Walk-Forward", "category": "产品",
     "definition": "滚动训练-验证-外推的回测方法，检验参数稳健性。",
     "calc": "窗口滚动：训练段拟合、验证段选择、外推段评估"},
    {"key": "oos", "term": "样本外(OOS)", "category": "产品",
     "definition": "未参与参数拟合的数据段，用于检验策略真实表现。",
     "calc": "70/30 切分，后 30% 段不触碰拟合"},
    {"key": "sharpe", "term": "夏普比率", "category": "产品",
     "definition": "单位风险的超额收益，衡量风险调整后收益。",
     "calc": "(年化收益-无风险)/年化波动"},
    {"key": "drawdown", "term": "回撤", "category": "产品",
     "definition": "净值从峰值到低点的最大跌幅。",
     "calc": "(峰-谷)/峰"},
    {"key": "winrate", "term": "胜率", "category": "产品",
     "definition": "评估命中/正确预测的比例，衡量评估质量。",
     "calc": "命中次数/总评估次数"},
    {"key": "portfolio", "term": "模拟组合", "category": "产品",
     "definition": "按策略合成因子构建的模拟持仓，跟踪实时盈亏。",
     "calc": "选 topN + 权重 + 逐日净值"},
    {"key": "data_quality", "term": "数据质量分", "category": "产品",
     "definition": "对数据完整性/一致性/时效性的分级评分。",
     "calc": "质量规则引擎打分 A-D 档"},
    {"key": "rbac", "term": "RBAC权限", "category": "产品",
     "definition": "基于角色的访问控制，按角色划分操作与数据范围。",
     "calc": "权限点注册表 + 内置/自定义角色"},
    # ── 补充至 60+ (6.1.1 A1 补齐) ─────────────
    {"key": "sector_rotation", "term": "行业轮动", "category": "策略",
     "definition": "资金在不同行业间轮动切换，跟随强势行业的策略。",
     "calc": "行业相对强度/资金流排序择强"},
    {"key": "index_enhance", "term": "指数增强", "category": "策略",
     "definition": "在跟踪指数基础上叠加选股/择时增强收益。",
     "calc": "基准指数 + 因子选股权重偏移"},
    {"key": "multifactor", "term": "多因子", "category": "策略",
     "definition": "多个因子加权合成选股信号。",
     "calc": "因子标准化后按权重合成打分"},
    {"key": "volatility", "term": "波动率", "category": "因子",
     "definition": "收益率的波动程度，衡量风险大小。",
     "calc": "收益率标准差(年化)"},
    {"key": "dividend_yield", "term": "股息率", "category": "因子",
     "definition": "每股分红相对股价的比例，衡量分红回报。",
     "calc": "每股股息/股价"},
    {"key": "bollinger", "term": "布林带", "category": "技术",
     "definition": "由中轨均线与上下轨构成的价格波动通道。",
     "calc": "中轨=MA20, 上下轨=±2倍标准差"},
    {"key": "dragon_head", "term": "龙头股", "category": "短线",
     "definition": "板块或市场中领涨的强势个股，情绪风向标。",
     "calc": "连板高度/成交/带动效应综合识别"},
    {"key": "data_freshness", "term": "数据新鲜度", "category": "数据源",
     "definition": "数据表最后更新时间与期望刷新间隔的符合度。",
     "calc": "最后成功时间 vs 期望间隔(过期标红)"},
]

GLOSSARY_BY_KEY: Dict[str, Dict] = {g["key"]: g for g in GLOSSARY}
