// V4.3 (方案A) 构建入口: 按 index.html 原始 script 顺序副作用导入全部业务 JS
// 由 gen_mainjs.py 生成, 顺序改动需同步 index.html 与本题

import '../js/themes.js'
import '../js/i18n.js'
import '../js/locales/zh-CN.js'
import '../js/locales/en.js'
import '../js/locales/ja.js'
import '../js/locales/ko.js'
import '../js/locales/zh-TW.js'
import '../js/pinyin.js'
import '../js/preferences.js'
import '../js/recent.js'
import '../js/icons.js'
import '../js/core.js'
import '../js/charts.js'
import '../js/ai.js'
import '../js/system.js'
import '../js/users.js'
import '../js/ai-chat.js'
import '../js/stock-pool.js'
import '../js/watchlist.js'
import '../js/portfolio.js'
import '../js/backtest-core.js'
import '../js/backtest.js'
import '../js/merrill.js'
import '../js/echarts-theme.js'
import '../js/components/sidebar.js'
import '../js/components/global-header.js'
import '../js/components/calendar-page.js'
import '../js/components/strategies-page.js'
import '../js/virtual-list-core.js'
import '../js/components/virtual-list.js'
import '../js/mobile-gestures.js'
import '../js/state-panel-core.js'
import '../js/components/state-panel.js'
import '../js/command-panel-core.js'
import '../js/onboarding-core.js'
import '../js/onboarding.js'
import '../js/empty-error.js'
import '../js/components/command-panel.js'
import '../js/components/dialogs/change-password.js'
import '../js/components/dialogs/shortcut-help.js'
import '../js/components/dialogs/tour.js'
import '../js/components/dialogs/menu-config.js'
import '../js/components/dialogs/add-group.js'
import '../js/components/dialogs/add-user.js'
import '../js/components/dialogs/batch-evaluate.js'
import '../js/components/dialogs/auto-evaluate.js'
import '../js/components/dialogs/index-detail.js'
import '../js/components/dialogs/setup-wizard.js'
import '../js/components/dialogs/merrill-detail.js'
import '../js/components/dialogs/stock-detail.js'
import '../js/components/history-record.js'
import '../js/app-logic/data.js'
import '../js/app-logic/market.js'
import '../js/app-logic/ops.js'
import '../js/app-logic/nav.js'
import '../js/app-logic/keys.js'
import '../js/app-logic/auth.js'
import '../js/app-logic/watch.js'
import '../js/app-logic/lifecycle.js'
import '../js/app-logic.js'

// V4.3-S3 (方案A): 页面组件懒加载 — 切换对应页面前由 __quantGoPage 动态 import
// 4 大页面组件(system/strategies/ai/research)合计 ~300KB raw, 延迟到进入页面时加载
window.__lazyLoaders = {
  system: () => import('../js/components/system-page.js'),
  ai: () => import('../js/components/ai-page.js'),
  research: () => import('../js/components/research-page.js'),
  shortterm: () => import('../js/components/shortterm-page.js'),
};
